# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# 1. Install Backend Dependencies
- script: |
    npm install
  displayName: 'Install Backend Dependencies'

# 2. Install and Build Frontend
- script: |
    npm install
    npm run build
  workingDirectory: 'admin-ui'
  displayName: 'Install and Build Frontend (admin-ui)'
